# Generated by Django 2.0.4 on 2018-04-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='dashboard.Sale'),
        ),
    ]
