# Generated by Django 2.0.4 on 2018-04-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180407_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
