# Generated by Django 2.0.4 on 2018-04-08 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180408_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='user',
            name='purchases',
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=None, to='dashboard.Sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(null=True, on_delete=None, to='dashboard.Store'),
        ),
    ]
