# Generated by Django 2.0.4 on 2018-04-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180408_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_usd',
        ),
    ]
