# Generated by Django 2.0.4 on 2018-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_product_total_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_usd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cod',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
