# Generated by Django 2.0.4 on 2018-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180409_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_local',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
